### ISSUE TITLE
Permalinks only work without trailing slash

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg-project.github.io#1]
Compare the following links:

https://homalg-project.github.io/pkg/MatroidGeneration

https://homalg-project.github.io/pkg/MatroidGeneration/

The first one redirects correctly, the second one gives a 404 Not found error. I think it would be good if both would redirect correctly to avoid confusion and possible problems (for example when replacing an existing link which has a trailing slash and forgetting about this problem).

**Comment by mohamed-barakat** [comment]
I made a try which does not seem to work (yet):

https://github.com/homalg-project/homalg-project.github.io/commit/1baa87d981401211679cd320efebc040d2714ea5

**Comment by mohamed-barakat** [comment]
With https://github.com/homalg-project/homalg-project.github.io/commit/e33aa2e30ff3dd0645d7898c18275f3b4643f0ae it worked :)

Maybe `PackageJanitor` should take over :)

**Comment by zickgraf** [comment]
Nice :-)

Shouldn't Jekyll itself be able to generate these files automatically? I would prefer such a solution to using `PackageJanitor`.

**Comment by mohamed-barakat** [comment]
Probably one can but I don't yet know how to do this.
