### ISSUE TITLE
Installation instructions not valid for Ubuntu 22.04

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg-project.github.io#10]
Ubuntu 22.04 does not include Julia in the repositories anymore (only in the Snap store, and there with outdated version 1.0), so `sudo apt-get install -y julia libjulia-dev` does not work.

**Comment by mohamed-barakat** [comment]
Shall we restrict to the older Ubuntu versions?

**Comment by zickgraf** [comment]
I'm not sure how aggressively Ubuntu advertises newer versions, but I assume that in the next months a significant share of the users will use Ubuntu 22.04. We could link here: https://julialang.org/downloads/platform/#linux_and_freebsd

**Comment by mohamed-barakat** [comment]
> We could link here: https://julialang.org/downloads/platform/#linux_and_freebsd

Good idea, I agree.
